include Makefile.common

CFLAGS += -DRAD_LINUX -DRAD_WARN -Wno-pointer-sign -Wno-gnu-designator
CFLAGS += $(shell sdl2-config --cflags)

LIB = $(shell sdl2-config --libs)

NAGI_NORM = ../bin/nagi

all:	nagi

nagi:	$(NAGI_NORM)

$(NAGI_NORM): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) $(LIB) -o $@

clean:
	$(RM) $(OBJ) $(NAGI_NORM) core

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@
